# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit, push]
default_language_version:
    python: python3
exclude: "deprecated"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-builtin-literals
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy # type annotations
        exclude: ^tests/,^venv/
-   repo: https://github.com/PyCQA/pylint
    rev: v2.17.4
    hooks:
    -   id: pylint
        exclude: error.py
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    -   id: codespell # spell-check source code
        args: ["-L", "textgraph,udo"] # comma separated stop words
        exclude: ^README.md|^NOTES.md|^examples
        language: python
        types: [text]
