name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
#  pre-commit:
#    name: Run pre-commit
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v3
#    - uses: pre-commit/action@v3.0.0

  test:
    name: Tests for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
      fail-fast: false
#    needs: pre-commit

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .
          pip install git+https://github.com/thunlp/OpenNRE
          pip install pre-commit pytest

      - name: Run tests
        run: |
          pytest
